### ISSUE TITLE
پاسخنامه م۲ دوره ۲۱

### ISSUE THREAD

**Issue by MEgooneh** [shaazzz/site#7]
کلید داره ولی آپلود نشده :

[link](https://opedia.ir/_media/%D8%B3%D9%88%D8%A7%D9%84%D8%A7%D8%AA_%D8%A7%D9%84%D9%85%D9%BE%DB%8C%D8%A7%D8%AF/%D9%85%D8%B1%D8%AD%D9%84%D9%87_%DB%8C_%D8%AF%D9%88%D9%85/%D8%AF%D9%88%D8%B1%D9%87_%DB%8C_%DB%B2%DB%B1/%DA%A9%D9%84%DB%8C%D8%AF21.jpg?w=56&h=120&t=1621330841&tok=60ddc5)

**Comment by ParsaAlizadeh** [comment]
ممنون 🙏🏻 
چندتا دوره دیگه رو هم چک کردم و کلید هاشون به آرشیو اضافه شده.
